# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0659b28d76207e07a2708a0dac016477367920de4271d6f5e67771b4f54b1c4dc1d249b9b8056e76cf34c8ace77ae238e24a19eddf116a53b600e2a82dc41fec

test:
  secret_key_base: 83c0126559b11c110501a15d07b310ab53937073b8d3bb829ecd6ba15c555aa6470db0cfc02c9874b0032540c026b3b990dd90a65cad0e3d0588686809aeacb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
